---
  - name: Add basic auth credentials and ensure permissions are set
    become: yes
    community.general.htpasswd:
      path: /etc/nginx/.auth_pass
      name: "{{ basic_auth.username }}"
      password: "{{ basic_auth.password }}"
      owner: root
      group: www-data
      mode: 0640