---
- name: debconf for pma
  become: yes
  debconf:
    name: phpmyadmin
    question: 'phpmyadmin/dbconfig-install'
    value: 'true'
    vtype: 'boolean'

- name: debconf for pma
  become: yes
  debconf:
    name: phpmyadmin
    question: 'phpmyadmin/app-password-confirm'
    value: "{{ mysql.phpmyadmin_password }}"
    vtype: 'password'

- name: debconf for pma
  become: yes
  debconf:
    name: phpmyadmin
    question: 'phpmyadmin/mysql/admin-pass'
    value: "{{ mysql.root_password }}"
    vtype: 'password'

- name: debconf for pma
  become: yes
  debconf:
    name: phpmyadmin
    question: 'phpmyadmin/mysql/app-pass'
    value: "{{ mysql.phpmyadmin_password }}"
    vtype: 'password'

- name: debconf for pma
  become: yes
  debconf: 
    name: phpmyadmin
    question: 'phpmyadmin/reconfigure-webserver'
    value: ''
    vtype: 'multiselect'

- name: install pma
  become: yes
  apt:
    pkg: phpmyadmin
    state: present

- name: configure phpmyadmin site
  become: yes
  file:
    src: /usr/share/phpmyadmin
    dest: /var/www/phpmyadmin
    state: link
    owner: phpmyadmin
    group: phpmyadmin
    mode: 0755
    