---
  - name: (Handler - NGINX Config) Check NGINX
    become: yes
    command: nginx -t
    args:
      chdir: /etc/nginx/
    register: config_check
    ignore_errors: true
    check_mode: false
    changed_when: false
    listen: (Handler - NGINX Config) Run NGINX

  - name: (Handler - NGINX Config) Print NGINX error if syntax check fails
    become: yes
    debug:
      var: config_check.stderr_lines
    failed_when: config_check.rc != 0
    when:
      - config_check.stderr_lines is defined
      - config_check.rc != 0
    listen: (Handler - NGINX Config) Run NGINX

  - name: (Handler - NGINX Config) Start/reload NGINX
    become: yes
    service:
      name: nginx
      state: reloaded
    when:
      - nginx_config_start | bool
      - not ansible_check_mode | bool
    listen: (Handler - NGINX Config) Run NGINX