---
  - name: Reboot host and wait for restart
    become: yes
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 10
      test_command: whoami