---
  - name: Setup Python
    become: yes
    raw: apt -y update && apt install -y python3

  - name: Update and upgrade apt packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Install System Packages
    become: yes
    apt:
      pkg: [ 'zip', 'unzip', 'curl', 'wget', 'xfonts-75dpi', 'python3-software-properties', 'python3-passlib' ]
      state: latest

  - name: Install Extra Packages
    become: yes
    apt:
      name: "{{ server.packages }}"
      state: latest
      update_cache: yes
    when: server.packages is defined

  - name: ClamAV Daily Scan Cron
    become: yes
    cron:
      name: "ClamAV Daily Scan"
      minute: "0"
      hour: "2"
      job: "/usr/local/sbin/clamscan_daily.sh > /dev/null 2>&1"

  - name: Reset folder/file permissions on www Cron
    become: yes
    cron:
      name: "Reset folder/file permissions on www"
      minute: "0"
      hour: "3"
      day: "1"
      month: "*/1"
      job: "/usr/local/sbin/perms.sh"

  - name: Creates an entry "MAILTO" in Cron
    become: yes
    cron:
      name: MAILTO
      env: yes
      job: "{{ user.admin.email }}"

  - name: Creates an entry "CRON_TZ=Europe/Paris" in Cron
    become: yes
    cron:
      name: CRON_TZ
      env: yes
      job: Europe/Paris
      insertafter: MAILTO

  - name: Modify postmaster aliase
    become: yes
    lineinfile:
      path: /etc/aliases
      regex: '^postmaster: '
      state: present
      insertafter: '^#postmaster: '
      line: "postmaster: root"

  - name: Modify clamav aliase
    become: yes
    lineinfile:
      path: /etc/aliases
      regex: '^clamav: '
      state: present
      insertafter: '^#clamav: '
      line: "clamav: root"

  - name: Add root to aliases
    become: yes
    lineinfile:
      path: /etc/aliases
      insertafter: EOF
      state: present
      owner: root
      group: root
      mode: 0644
      line: "root: {{ user.admin.email }}"
    notify: reload newaliases

  - name: Set enable auto updates to true
    become: yes
    debconf:
      name: locales
      question: unattended-upgrades/enable_auto_updates
      value: 'True'
      vtype: 'string'
  
  - name: Turn on unattended security updates
    become: yes
    shell: dpkg-reconfigure -f noninteractive unattended-upgrades

  - name: Copy 50unattended-upgrades template
    become: yes
    template:
      src: 50unattended-upgrades.j2
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      owner: root
      group: root
      mode: 0644
  
  - name: Copy 20auto-upgrades template
    become: yes
    template:
      src: 20auto-upgrades.j2
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      owner: root
      group: root
      mode: 0644