---
  - name: ensure timezone is set in cli php7.4.ini
    become: yes
    lineinfile:
        dest: /etc/php/7.4/cli/php.ini
        regexp: '^;date.timezone ='
        line: 'date.timezone = {{ server.timezone }}'